services:
  _defaults:
    autowire: true
    bind:
      $packages: '%kernel.packages%'
      $searchLogger: "@monolog.logger.huh_search"

  HeimrichHannot\SearchBundle\Command\RebuildSearchIndexCommand:
    tags: ['console.command']