services:
  _defaults:
    public: true
    autowire: true
    bind:
      $bundleConfig: '%huh_search%'
      $searchLogLogger: "@monolog.logger.huh_search_log"

  HeimrichHannot\SearchBundle\EventListener\CustomizeSearchListener: ~
  HeimrichHannot\SearchBundle\EventListener\GeneratePageListener: ~
  HeimrichHannot\SearchBundle\EventListener\IndexPageListener: ~
  HeimrichHannot\SearchBundle\EventListener\LoadDataContainerListener: ~
