services:
  _defaults:
    public: true
    autowire: true
  _bind:
    $bundleConfig: '%huh_search%'

  HeimrichHannot\SearchBundle\EventListener\CustomizeSearchListener: ~
  HeimrichHannot\SearchBundle\EventListener\LoadDataContainerListener: ~